site_name: My Docs
site_url: https://mydomain.org/mysite
theme: 
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: yellow
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

# extra:
#   social: #Qui vi allego i link dei miei rispettivi social! 
#     - type: "github"
#       link: "https://github.com/PistilliGiulia"
#     - type: "instagram"
#       link: "https://www.instagram.com/giulia.pistilli/"

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - NOI CHI SIAMO?:
    - ECCOCI QUA!: coding/my-first-java-file.md
  - About:
    - About Me: about/about.md
    - Childhood: about/childhood.md
  - Tags: tags.md
  - Blog:
    - blog/index.md
    